/**
 * Generates packages/sync/src/providers/microsoft/windows-zones.ts from CLDR
 * supplemental windowsZones.xml. Re-run when CLDR updates the mapping table.
 *
 *   bun run packages/scripts/src/commands/generate-windows-zones.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const CLDR_WINDOWS_ZONES_URL =
  "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml";

const OUTPUT_PATH = resolve(
  import.meta.dir,
  "../../../sync/src/providers/microsoft/windows-zones.ts",
);

interface MapZoneRow {
  readonly windows: string;
  readonly territory: string;
  readonly iana: string;
}

const DEPRECATED_IANA_ALIASES: Readonly<Record<string, string>> = {
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "Europe/Kiev": "Europe/Kyiv",
  "America/Godthab": "America/Nuuk",
  "Asia/Calcutta": "Asia/Kolkata",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Katmandu": "Asia/Kathmandu",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "Etc/UTC": "UTC",
};

function canonicalIana(iana: string): string {
  return DEPRECATED_IANA_ALIASES[iana] ?? iana;
}

function parseMapZones(xml: string): MapZoneRow[] {
  const rows: MapZoneRow[] = [];
  const re =
    /<mapZone other="([^"]+)" territory="([^"]+)" type="([^"]+)"\s*\/>/g;
  for (const match of xml.matchAll(re)) {
    rows.push({
      windows: match[1]!,
      territory: match[2]!,
      iana: match[3]!,
    });
  }
  return rows;
}

function buildMaps(rows: MapZoneRow[]): {
  windowsToIana: ReadonlyMap<string, string>;
  ianaToWindows: ReadonlyMap<string, string>;
} {
  const windowsToIana = new Map<string, string>();
  for (const row of rows) {
    if (row.territory !== "001") continue;
    windowsToIana.set(row.windows, canonicalIana(row.iana));
  }

  const ianaToWindows = new Map<string, string>();
  for (const [windows, iana] of [...windowsToIana.entries()].sort((a, b) =>
    a[0].localeCompare(b[0]),
  )) {
    if (!ianaToWindows.has(iana)) {
      ianaToWindows.set(iana, windows);
    }
  }

  return { windowsToIana, ianaToWindows };
}

function serializeMap(
  name: string,
  entries: ReadonlyMap<string, string>,
): string {
  const lines = [...entries.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => {
      const keyLiteral = key === "UTC" ? "UTC" : JSON.stringify(key);
      return `  ${keyLiteral}: ${JSON.stringify(value)},`;
    });
  return `const ${name}: Readonly<Record<string, string>> = {\n${lines.join("\n")}\n};\n`;
}

async function main(): Promise<void> {
  const response = await fetch(CLDR_WINDOWS_ZONES_URL);
  if (!response.ok) {
    throw new Error(
      `Failed to download CLDR windowsZones.xml: HTTP ${response.status}`,
    );
  }
  const xml = await response.text();
  const { windowsToIana, ianaToWindows } = buildMaps(parseMapZones(xml));

  const source = `// Generated by packages/scripts/src/commands/generate-windows-zones.ts
// Do not edit by hand. Re-run the script to refresh from CLDR.

${serializeMap("WINDOWS_TO_IANA", windowsToIana)}
${serializeMap("IANA_TO_WINDOWS", ianaToWindows)}
export function windowsZoneToIana(windowsZone: string): string {
  const iana = WINDOWS_TO_IANA[windowsZone];
  if (!iana) {
    throw new Error(\`Unknown Windows time zone: \${windowsZone}\`);
  }
  return iana;
}

export function ianaZoneToWindows(ianaZone: string): string {
  const windows = IANA_TO_WINDOWS[ianaZone];
  if (!windows) {
    throw new Error(\`No Windows time zone mapping for IANA zone: \${ianaZone}\`);
  }
  return windows;
}

export function listWindowsZones(): readonly string[] {
  return Object.keys(WINDOWS_TO_IANA);
}
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, source, "utf8");
  console.log(
    `Wrote ${OUTPUT_PATH} (${windowsToIana.size} Windows zones, ${ianaToWindows.size} IANA reverse entries)`,
  );
}

await main();
