export const gcalListDemo = {
  kind: "calendar#calendarList",
  etag: '"p32of5lkbqidfa0g"',
  nextSyncToken: "CLDy1ovUmvUCEhJ0eUBzd2l0Y2hiYWNrLnRlY2g=",
  items: [
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632953194377000"',
      id: "***REMOVED***",
      summary: "Switchback",
      timeZone: "America/Chicago",
      colorId: "16",
      backgroundColor: "#7397b5",
      foregroundColor: "#000000",
      selected: true,
      accessRole: "owner",
      defaultReminders: [
        {
          method: "popup",
          minutes: 10,
        },
      ],
      notificationSettings: {
        notifications: [
          {
            type: "eventCreation",
            method: "email",
          },
          {
            type: "eventChange",
            method: "email",
          },
          {
            type: "eventCancellation",
            method: "email",
          },
          {
            type: "eventResponse",
            method: "email",
          },
        ],
      },
      primary: true,
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632953195330000"',
      id: "addressbook#contacts@group.v.calendar.google.com",
      summary: "Birthdays",
      description:
        "Displays birthdays, anniversaries, and other event dates of people in Google Contacts.",
      timeZone: "America/Chicago",
      colorId: "8",
      backgroundColor: "#3d405b",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "reader",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632953196045000"',
      id: "cd43evntemvclci6hoe806hmdo@group.calendar.google.com",
      summary: "Holiday & Travel",
      timeZone: "America/Chicago",
      colorId: "11",
      backgroundColor: "#f2cc8f",
      foregroundColor: "#000000",
      selected: true,
      accessRole: "owner",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632953197323000"',
      id: "6ommofvipenb5vj30kv0rmkbi8@group.calendar.google.com",
      summary: "Marty",
      timeZone: "America/Denver",
      colorId: "15",
      backgroundColor: "#63d2ff",
      foregroundColor: "#000000",
      selected: true,
      accessRole: "owner",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632953197913000"',
      id: "***REMOVED***@gmail.com",
      summary: "*Miscellaneous*",
      timeZone: "America/Chicago",
      colorId: "8",
      backgroundColor: "#087e8b",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "owner",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632969845493000"',
      id: "hc7a7nqfoje5u61pdedt4ogil8@group.calendar.google.com",
      summary: "Acuity",
      timeZone: "America/Denver",
      colorId: "1",
      backgroundColor: "#7f0799",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "reader",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1632969847030000"',
      id: "***REMOVED***",
      summary: "Commitments",
      timeZone: "America/Chicago",
      colorId: "1",
      backgroundColor: "#7f0799",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "reader",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1633389298170000"',
      id: "49q3td7e05uiffvnm4kb67i2hc@group.calendar.google.com",
      summary: "Location",
      description: "Where I'm at when",
      timeZone: "America/Chicago",
      colorId: "1",
      backgroundColor: "#795548",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "owner",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1638220059360000"',
      id: "092les60i087mo00voo5m369v38467l0@import.calendar.google.com",
      summary: "BuJo_U",
      timeZone: "UTC",
      colorId: "20",
      backgroundColor: "#cabdbf",
      foregroundColor: "#000000",
      accessRole: "reader",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
    {
      kind: "calendar#calendarListEntry",
      etag: '"1640995478839000"',
      id: "c_vgq4gkr1l895u2tdgvkqain5ss@group.calendar.google.com",
      summary: "United States holidays",
      timeZone: "UTC",
      colorId: "8",
      backgroundColor: "#3d405b",
      foregroundColor: "#ffffff",
      selected: true,
      accessRole: "owner",
      defaultReminders: [],
      conferenceProperties: {
        allowedConferenceSolutionTypes: ["hangoutsMeet"],
      },
    },
  ],
};
