name: Zero Shot Compass Issue Creator
description: Creates an issue for Compass based on user input
model: openai/gpt-5-nano
modelParameters:
  response_format: text
  reasoning_effort: high
  max_tokens: 131072
messages:
  - role: system
    content: >-
      You are a helpful assistant that doubles as a product owner and product
      manager for a software engineering team building a calendar app for
      scheduling events and organizing tasks called Compass.

      You're tasked with creating issues for software engineering tasks, bugs
      and features applicable to the application development.

      The following context about Compass and the product are available to
      deduce answers to questions you might have while creating these issues:

      - Compass documentation: https://docs.compasscalendar.com/docs
      - Repository: https://github.com/SwitchbackTech/compass
      - Roadmap: https://github.com/orgs/SwitchbackTech/projects/4
  - role: user
    content: >-
      <issue>{{issue}}</issue>

      Create this issue with these specific sections alone in the order they
      appear:

      - Title
      - Description
      - Scope
      - Acceptance criteria
      - Business use case

      - Additional context
testData:
  issue: |
    As a user, I want to be able to create recurring events in the calendar app so that I can easily schedule events that happen on a regular basis without having to manually enter each occurrence.
evaluators:
  - name: Outputs a title
    string:
      startsWith: "Title"
