// server to client events
export const EVENT_CHANGED = "EVENT_CHANGED";
export const SOMEDAY_EVENT_CHANGED = "SOMEDAY_EVENT_CHANGED";
export const EVENT_RECEIVED = "EVENT_RECEIVED";

export const RESULT_IGNORED = "IGNORED";
export const RESULT_NOTIFIED_CLIENT = "NOTIFIED_CLIENT";

export const USER_METADATA = "USER_METADATA";

export const IMPORT_GCAL_START = "IMPORT_GCAL_START";
export const IMPORT_GCAL_END = "IMPORT_GCAL_END";

export const GOOGLE_REVOKED = "GOOGLE_REVOKED";

// client to server events
export const EVENT_CHANGE_PROCESSED = "EVENT_CHANGE_PROCESSED";
export const SOMEDAY_EVENT_CHANGE_PROCESSED = "SOMEDAY_EVENT_CHANGE_PROCESSED";

export const FETCH_USER_METADATA = "FETCH_USER_METADATA";
