export const EVENT_CHANGE_PROCESSED = "EVENT_CHANGE_PROCESSED";
export const EVENT_CHANGED = "EVENT_CHANGED";
export const EVENT_RECEIVED = "EVENT_RECEIVED";

export const RESULT_IGNORED = "IGNORED";
export const RESULT_NOTIFIED_CLIENT = "NOTIFIED_CLIENT";

export const IMPORT_GCAL_START = "IMPORT_GCAL_START";
export const IMPORT_GCAL_END = "IMPORT_GCAL_END";
