import {
  CALENDAR_DECK_INDENT,
  CALENDAR_DECK_MIN_WIDTH,
  CALENDAR_DECK_RIGHT_RESERVE,
  CALENDAR_DRAFT_DURATION_MIN,
  CALENDAR_DRAFT_PADDING_BOTTOM,
  CALENDAR_EVENT_ALLDAY_GAP,
  CALENDAR_EVENT_ALLDAY_HEIGHT,
  CALENDAR_EVENT_ALLDAY_ROW_HEIGHT,
  CALENDAR_EVENT_PADDING_RIGHT,
  CALENDAR_EVENT_WIDTH_MINIMUM,
  CALENDAR_GRID_EVENT_TIME_LABEL_FONT_SIZE,
  CALENDAR_GRID_EVENT_TIME_LABEL_OPACITY,
  CALENDAR_GRID_EVENT_TITLE_LINE_HEIGHT,
  CALENDAR_GRID_MARGIN_LEFT,
  CALENDAR_GRID_PADDING_BOTTOM,
  CALENDAR_GRID_TIME_STEP,
  CALENDAR_MIN_EVENT_HEIGHT_FOR_TIME_LABEL,
  CALENDAR_MIN_EVENT_WIDTH_FOR_TIME_LABEL,
  CALENDAR_TIMED_EVENT_COLUMN_INSET,
  CALENDAR_TIMED_VISIBLE_HOURS,
} from "@web/layout/calendar-grid/calendarGrid.constants";

export const AFTER_TMRW_MULTIPLE = 1.5;

export const DIVIDER_GRID = 1;

export const DRAFT_DURATION_MIN = CALENDAR_DRAFT_DURATION_MIN;
export const DRAFT_PADDING_BOTTOM = CALENDAR_DRAFT_PADDING_BOTTOM;

export const EVENT_ALLDAY_HEIGHT = CALENDAR_EVENT_ALLDAY_HEIGHT;
/** Gap between each allday event, found by experimenting with what 'looked right' */
export const EVENT_ALLDAY_GAP = CALENDAR_EVENT_ALLDAY_GAP;
/** Height of the row containing the all-day event. Not to be confused with `EVENT_ALLDAY_HEIGHT` */
export const EVENT_ALLDAY_ROW_HEIGHT = CALENDAR_EVENT_ALLDAY_ROW_HEIGHT;
export const EVENT_PADDING_RIGHT = CALENDAR_EVENT_PADDING_RIGHT;
export const TIMED_EVENT_COLUMN_INSET = CALENDAR_TIMED_EVENT_COLUMN_INSET;
export const GRID_EVENT_TIME_LABEL_FONT_SIZE =
  CALENDAR_GRID_EVENT_TIME_LABEL_FONT_SIZE;
export const GRID_EVENT_TIME_LABEL_OPACITY =
  CALENDAR_GRID_EVENT_TIME_LABEL_OPACITY;
export const GRID_EVENT_TITLE_LINE_HEIGHT =
  CALENDAR_GRID_EVENT_TITLE_LINE_HEIGHT;
/** Minimum rendered event height (px) to show the time label below the title.
 *  Below this the label is suppressed to prevent overflow on short events.
 *  At typical hourHeight (~65px/hr): 30-min ≈ 33px (hidden), 45-min ≈ 49px (shown). */
export const MIN_EVENT_HEIGHT_FOR_TIME_LABEL =
  CALENDAR_MIN_EVENT_HEIGHT_FOR_TIME_LABEL;
export const MIN_EVENT_WIDTH_FOR_TIME_LABEL =
  CALENDAR_MIN_EVENT_WIDTH_FOR_TIME_LABEL;
export const EVENT_WIDTH_MINIMUM = CALENDAR_EVENT_WIDTH_MINIMUM;

export const DECK_INDENT = CALENDAR_DECK_INDENT;
export const DECK_RIGHT_RESERVE = CALENDAR_DECK_RIGHT_RESERVE;
export const DECK_MIN_WIDTH = CALENDAR_DECK_MIN_WIDTH;

export const FLEX_TODAY = 21.4;
export const FLEX_TMRW = 18.6;
export const FLEX_EQUAL = 14.285714285714286; // 100 / 7
const HEADER_HEIGHT = 40;

const PAGE_MARGIN_TOP = 35;
const PAGE_MARGIN_X = 25;

const WEEK_DAYS_HEIGHT = 26;
const WEEK_DAYS_MARGIN_Y = 22;

export const GRID_PADDING_BOTTOM = CALENDAR_GRID_PADDING_BOTTOM;
export const GRID_MARGIN_LEFT = CALENDAR_GRID_MARGIN_LEFT;
export const GRID_TIME_STEP = CALENDAR_GRID_TIME_STEP;
export const WEEK_TIMED_VISIBLE_HOURS = CALENDAR_TIMED_VISIBLE_HOURS;
export const GRID_X_START = PAGE_MARGIN_X + GRID_MARGIN_LEFT;
export const GRID_Y_START =
  PAGE_MARGIN_TOP + HEADER_HEIGHT + WEEK_DAYS_HEIGHT + WEEK_DAYS_MARGIN_Y;
export const WEEK_GRID_TRACK_MIN_WIDTH =
  GRID_MARGIN_LEFT + EVENT_WIDTH_MINIMUM * 7;

export const SIDEBAR_MONTH_HEIGHT = 275;
