export {
  CONTACTS_FEATURE_SCOPES,
  GOOGLE_SCOPE_CALENDAR_EVENTS,
  GOOGLE_SCOPE_CALENDAR_READONLY,
  GOOGLE_SCOPE_CONTACTS_OTHER_READONLY,
  GOOGLE_SCOPE_CONTACTS_READONLY,
  GOOGLE_SCOPE_USERINFO_EMAIL,
  GOOGLE_SCOPES,
  googleScopesForFeatures,
} from "@core/providers/google.scopes";
