export const SOMEDAY_EVENT_ROW_HEIGHT = 30;
export const SOMEDAY_EVENT_ROW_VERTICAL_MARGIN = 2;
export const SOMEDAY_EVENT_ROW_FOOTPRINT =
  SOMEDAY_EVENT_ROW_HEIGHT + SOMEDAY_EVENT_ROW_VERTICAL_MARGIN * 2;
