name: Feature Request
description: You want something added to the app
labels: [enhancement]
projects: [SwitchbackTech/4]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added.
      placeholder: New Thing should work like this ...

  - type: textarea
    attributes:
      label: Use Case
      description: Explain the use case for this feature. How will it benefit users?
      placeholder: This'll save users time by ...

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        - Links to similar features in other apps
        - User research or feedback
        - Technical considerations
        - Screenshots or mockups
