name: Bug Report 🐞
description: You found something wrong
labels: [bug]
projects: [SwitchbackTech/4]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    attributes:
      label: Where did this happen?
      multiple: true
      options:
        - Hosted (app.compasscalendar.com)
        - Local code with an up-to-date main branch

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior...

  - type: textarea
    attributes:
      label: Current Behavior
      description: What went wrong? If applicable, add screenshots or videos
      placeholder: Describe the current behavior...

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Include a step-by-step guide, along with any stack traces, screenshots, or screen recordings.
      placeholder: |
        1. Go to calendar view
        2. Click on an event
        3. Try to edit the event
        4. See error message
      required: true

  - type: textarea
    attributes:
      label: Possible Solution
      description: Suggest a reason for the bug or how to fix it.
      placeholder: If you already know how we could solve this, describe it here...

  - type: textarea
    attributes:
      label: Context
      description: How has this issue affected you as a user? What were you trying to accomplish? Any workarounds?
      placeholder: Describe the context...
