export enum Sync_AsyncStateContextReason {
  EVENT_CHANGED = "EVENT_CHANGED",
  SOMEDAY_EVENT_CHANGED = "SOMEDAY_EVENT_CHANGED",
  IMPORT_COMPLETE = "IMPORT_COMPLETE",
  GOOGLE_REVOKED = "GOOGLE_REVOKED",
}
