export const REMINDERS = [
  "Automate repetitive tasks",
  "Create with the heart; build with the mind.",
  "When you have to make a choice and don’t make it, that in itself is a choice",
  "Strive not to be a success, but rather to be of value",
  "The best way out is always through",
  "Plans are nothing; planning is everything",
  "Failure is an event, not a person",
  "Lock in until the presentation",
  "What we fear doing most is usually what we most need to do",
  "You don’t need a new plan. You need a commitment",
  "If you spend too much time thinking about a thing, you’ll never get it done",
  "A small deed done is better than a great intention",
  "You can do anything, but not everything",
  "If you want an easy job to seem mighty hard, just keep putting it off",
  "You may delay, but time will not",
  "Edit your life frequently and ruthlessly. It’s your masterpiece after all",
  "Identify the essential. Eliminate the rest",
  "Intentionality beats complexity.",
  "Focus on what you control; ignore the rest.",
  "Do fewer things, work at a natural pace, and obsess over quality.",
  "Keep only those things that speak to your heart.",
  "There are 168 hours a week—plenty to fit what matters.",
  "A schedule defends from chaos and whim.",
  "Clear is kind. Unclear is unkind.",
  "Clarity comes from action, not thought.",
  "Nothing will work unless you do.",
];
