export const REMINDERS = [
  "Create with the heart; build with the mind.",
  "When you have to make a choice and don’t make it, that in itself is a choice",
  "Strive not to be a success, but rather to be of value",
  "The best way out is always through",
  "Plans are nothing; planning is everything",
  "Failure is an event, not a person",
  "Lock in until the presentation",
  "What we fear doing most is usually what we most need to do",
  "You don’t need a new plan. You need a commitment",
  "If you spend too much time thinking about a thing, you’ll never get it done",
  "A small deed done is better than a great intention",
  "You can do anything, but not everything",
  "If you want an easy job to seem mighty hard, just keep putting it off",
  "You may delay, but time will not",
  "Edit your life frequently and ruthlessly. It’s your masterpiece after all",
  "Identify the essential. Eliminate the rest",
  "Intentionality beats complexity.",
  "Focus on what you control; ignore the rest.",
  "Do fewer things, work at a natural pace, and obsess over quality.",
  "Keep only those things that speak to your heart.",
  "There are 168 hours a week—plenty to fit what matters.",
  "A schedule defends from chaos and whim.",
  "Clear is kind. Unclear is unkind.",
  "Clarity comes from action, not thought.",
  "Nothing will work unless you do.",
  "Do, or do not. There is no try.",
  "This is your life and it's ending one minute at a time.",
  "If you can't do great things, do small things in a great way",
  "Do today what others won't and achieve tomorrow what others can't",
  "Rule your mind or it will rule you",
  "If you don’t risk anything, you risk even more",
  "Procrastination is like a credit card: a lot of fun until you get the bill",
  "Well done is better than well said.",
  "Your time is limited, so don't waste it living someone else's life",
  "The key is in not spending time, but in investing it.",
  "Time you enjoy wasting, was not wasted",
  "All we have to decide is what to do with the time that is given to us",
  "The two most powerful warriors are patience and time",
  "Lost time is never found again",
  "Plans are nothing; planning is everything",
  "Don’t wait. The time will never be just right",
  "The secret of your future is hidden in your daily routine",
  "The best thing about the future is that it comes one day at a time",
  "Freedom without discipline is chaos",
  "Discipline is choosing between what you want now, and what you want most",
  "Don’t let yesterday take up too much of today",
  "The successful warrior is the average man, with a laser-like focus",
  "A year from now you may wish you had started today",
  "Work hard in silence, let your success be your noise.",
  "Success is walking from failure to failure with no loss of enthusiasm",
  "It does not matter how slowly you go so long as you do not stop.",
  "There is no innovation and creativity without failure.",
  "Don’t wait for inspiration. It comes while working.",
  "Failure is success in progress.",
  "The problem with doing nothing is that you never know when you’re finished",
  "Action is the foundational key to all success.",
];
