name: Deploy staging

on:
  workflow_call:
    inputs:
      tag:
        description: 'Release tag being deployed, such as v1.2.3'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag being deployed, such as v1.2.3'
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy-cloud:
    name: Deploy to staging-cloud
    uses: ./.github/workflows/_deploy-environment.yml
    with:
      tag: ${{ inputs.tag }}
      environment: staging-cloud
    secrets: inherit

  deploy-selfhosted:
    name: Deploy to staging-selfhosted
    uses: ./.github/workflows/_deploy-environment.yml
    with:
      tag: ${{ inputs.tag }}
      environment: staging-selfhosted
    secrets: inherit
