name: Test

on: [push]

jobs:
  install-test-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: Run tests
        env:
          TZ: ${{ vars.TZ }}
        run: |
          yarn test
