name: Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [core, web, backend, scripts]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Run ${{ matrix.project }} tests
        env:
          TZ: ${{ vars.TZ }}
        run: |
          yarn test ${{ matrix.project }}
